"""add firstTime status

Revision ID: 0466ce44de96
Revises: daa767874222
Create Date: 2025-12-25 00:27:18.643350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0466ce44de96'
down_revision = 'daa767874222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_time', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_first_time')

    # ### end Alembic commands ###
