"""Vibe row in rooms

Revision ID: 44795a5da4e2
Revises: db450cf63dba
Create Date: 2025-11-30 16:26:18.646835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44795a5da4e2'
down_revision = 'db450cf63dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vibe', sa.String(length=50), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('vibe')

    # ### end Alembic commands ###
